### ISSUE TITLE
I am getting the following error, after setting up as per instructions in README

### ISSUE THREAD

**Issue by jaffamonkey** [ziprandom/cucumberjs-json-api-mocking#2]
I am getting the following error, after setting up as per instructions in README, to use the existing steps.  Have I missed something glaringly obvious? tried downgrading cucumber version, but still same error.

```
/home/jaffamonkey/projects/HEE_TIS_REVALIDATION/bdd/node_modules/cucumber/lib/cucumber/runtime/event_broadcaster.js:30
            throw error;
            ^
ReferenceError: node_modules/cucumber/lib/cucumber/support_code/library.js:15 client is not defined
    at /home/jaffamonkey/projects/HEE_TIS_REVALIDATION/bdd/node_modules/cucumberjs-json-api-mocking/lib/api_mock_steps.js:12:5
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by ziprandom** [comment]
duplicates #3
